apiVersion: v1
kind: Secret
metadata:
  [cite_start]name: checkout-prd-checkout-api-secrets [cite: 5]
  [cite_start]namespace: checkout-prd [cite: 5]
[cite_start]type: Opaque [cite: 5]
data:
  api_key: NWM3YTRkOWI2ZThmMmMwYTFiOWU4ZDdjNmI1YTRmM2UyZDFjMGI5YThmN2U2ZDVjNGIzYTJmMWUwZDljOGI3YTZmNWU0ZDNj
  active_campaign_api_token: ODNiZDllZTU0NTNjNzNhMmU5YTJjYzU5NzhlZTNmZDdmYzIzYjk5YTc2MzVlZTEwZDAyOWQ3NjBkZmVjYTM1NTE3ZGVkZGUw
  db_host: MTAuNy4yMS44
  db_username: cG9zdGdyZXM=
  db_password: dlA0QTRaeHcjYWVuVXlHITl6dklwdVhDMw==
  db_database: Y2hlY2tvdXQtYXBp
  asaas_api_key: JGFhY3RfWVRVNVlURTBNMk0yTjJJNE1UbGlOemswWVRJNU4yVTVNemRqTldabU5EUTZPakF3TURBd01EQXdNREF3TURBeE9EZzRNak02T2lSaFlXTm9YekUzTURnMU5tTmxMV1JpWVdVdE5EWmhaQzA1WVRrNUxUTTBZek5qT1RrM05XRTNOdz09
  clm_new_org_token: SlJTN3BIQ2I1b214bGt1RU5oUGc5YkJW
  customerx_api_token: NmNlYTI2NjU2ODRhYjIxYWE0ZTNiODIwY2Y3NzE5MjQ=
  customerx_api_base: aHR0cHM6Ly9hcGkuY3VzdG9tZXJ4LmNvbS5ici9hcGkvdjE=
