name: sync-branches

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  workflows: write    # <--- ESSENCIAL: Permite criar branches com workflows

jobs:
  reset-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4
        with:
          ref: main # Garante que estamos na main/master
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Limpar e Criar Branch
        run: |
          # Define o nome da branch conforme sua demanda (stg/dia-mes-ano)
          DATE=$(date +'%d-%m-%Y')
          BRANCH_NAME="stg/$DATE"

          echo "Tentando limpar branches antigas..."
          # O '|| true' faz o comando ignorar se a branch não existir
          git push origin --delete $BRANCH_NAME || true
          git push origin --delete staging || true

          # Cria a nova branch a partir da main atual
          git checkout -b $BRANCH_NAME

          # Sobe para o repositório
          git push origin $BRANCH_NAME
