name: Automação Semanal Staging

on:
  schedule:
    - cron: '0 0 * * 1' # Toda segunda à meia-noite
  workflow_dispatch:   # Botão para você testar agora

permissions:
  contents: write      # <--- ESSENCIAL: Resolve o erro 403
  workflows: write

jobs:
  reset-staging:
    runs-on: ubuntu-latest
    steps:
      steps:
      - name: Checkout Código
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Limpar e Criar Staging Branch
        run: |
          # Define a data e o nome da branch
          DATA=$(date +'%d-%m-%Y')
          BRANCH_NAME="stg/$DATA"
          # Se a branch já existir no remoto, ela é apagada
          if git ls-remote --exit-code --heads origin $BRANCH_NAME; then
            echo "Branch $BRANCH_NAME já existe. Deletando para resetar..."
            git push origin --delete $BRANCH_NAME || true
          fi
          # Cria a branch localmente e envia ao GitHub
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME

      - name: Reset Staging de Main
        run: |
          git config user.name "Github Action"
          git config user.email "action@github.com"

          # Garante que a staging seja deletada e recriada da master
          git push origin --delete staging || echo "Branch staging inexistente"
          git checkout -b staging origin/main
          git push origin staging
