name: sync-branches

on:
  workflow_dispatch:

jobs:
  criar-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Criar branch sem workflows
        run: |
          DATE=$(date +'%d-%m-%Y')
          BRANCH_NAME="stg/$DATE"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git checkout -b $BRANCH_NAME

          # 🔥 remove workflows
          rm -rf .github

          git add .
          git commit -m "branch limpa" || true

          git push origin $BRANCH_NAME
